Repository rust-unofficial/patterns, pull requests merged in 2021-01, with the labels that each got.

#111 Hosting mdbook with gh-pages
  .env
  .github/workflows/gh-pages.yml
  .gitignore
  README.md
  SUMMARY.md
  anti_patterns/README.md
  book.toml
  idioms/README.md
  patterns/README.md
Labels: addition, review

#115 add Continuous Integration
  .github/workflows/ci.yml
Labels: addition

#69 Fix wording in "Fold" pattern
  patterns/fold.md
Labels: fix, lgtm

#117 Add introduction
  README.md
  SUMMARY.md
  anti_patterns/README.md
  functional/README.md
  idioms/README.md
  intro.md
  patterns/README.md
  patterns/newtype.md
  refactoring/README.md
Labels: addition, enhancement, review, zombie

#125 Fix 404
  patterns/README.md
Labels: fix

#124 Add doc tests to CI
  .github/workflows/ci.yml
  anti_patterns/deny-warnings.md
  anti_patterns/deref.md
  idioms/ctor.md
  idioms/default.md
  idioms/deref.md
  idioms/dtor-finally.md
  idioms/on-stack-dyn-dispatch.md
  idioms/pass-var-to-closure.md
  idioms/priv-extend.md
  idioms/rustdoc-init.md
  idioms/temporary-mutability.md
  patterns/RAII.md
  patterns/builder.md
  patterns/compose-structs.md
  patterns/fold.md
  patterns/newtype.md
  patterns/visitor.md
Labels: addition, enhancement

#121 Fixing outdated link to rust-postgress
  README.md
Labels: fix

#102 Adding Nick Camerons talk at PDXRust 2016 to additional resources section
  SUMMARY.md
  additional_resources.md
Labels: enhancement, lgtm

#123 Contribution guide
  CONTRIBUTING.md
  README.md
  template.md
Labels: addition, needed-discussion

#58 added information on --cap-lints to deny-warnings antipattern
  anti_patterns/deny-warnings.md
Labels: enhancement, lgtm

#127 Fix typo in filename
  README.md
Labels: fix

#128 Remove reference to rust_rocks.md
  intro.md
Labels: fix

#129 Fixing links
  intro.md
Labels: fix

#133 Remove Entry API due to being a template copy
  SUMMARY.md
Labels: fix

#140 Marking Motivation in Compose Structs as TODO
  patterns/compose-structs.md
Labels: enhancement

#139 CONTRIBUTING: explain how to test the book
  CONTRIBUTING.md
Labels: enhancement

#142 Remove templated late bounds from summary
  SUMMARY.md
Labels: fix

#136 Update compose structs compile error example for NLL
  patterns/compose-structs.md
Labels: enhancement

#137 Fix on-stack dispatch example
  idioms/on-stack-dyn-dispatch.md
Labels: enhancement

#134 Fix default idiom example
  idioms/default.md
Labels: enhancement

#144 README: remove Table of Contents
  README.md
Labels: enhancement

#143 fix internal links
  SUMMARY.md
  anti_patterns/index.md
  functional/index.md
  idioms/index.md
  intro.md
  patterns/index.md
  refactoring/README.md
  refactoring/index.md
Labels: fix

#90 Make builder pattern more practical
  patterns/builder.md
Labels: enhancement, review

#150 Create url-check.yml
  .github/workflows/url-check-config.json
  .github/workflows/url-check-on-change.yml
  .github/workflows/url-check-periodic.yml
  refactoring/index.md
Labels: addition

#157 spelling mistake
  idioms/dtor-finally.md
Labels: fix

#29 Use coercion for arguments
  SUMMARY.md
  idioms/coercion-arguments.md
Labels: addition, review

#153 Use a problem as the intro for newtype pattern
  patterns/newtype.md
Labels: enhancement, review

#162 Updating mdbook
  .env
Labels: fix

#163 apply markdownlint to project
  .markdownlint.yaml
  CONTRIBUTING.md
  README.md
  SUMMARY.md
  anti_patterns/deref.md
  anti_patterns/index.md
  idioms/coercion-arguments.md
  idioms/concat-format.md
  idioms/ctor.md
  idioms/deref.md
  idioms/dtor-finally.md
  idioms/mem-replace.md
  idioms/on-stack-dyn-dispatch.md
  idioms/pass-var-to-closure.md
  idioms/priv-extend.md
  idioms/rustdoc-init.md
  idioms/temporary-mutability.md
  intro.md
  patterns/RAII.md
  patterns/builder.md
  patterns/compose-structs.md
  patterns/entry.md
  patterns/fold.md
  patterns/index.md
  patterns/late-bounds.md
  patterns/newtype.md
  patterns/visitor.md
  refactoring/index.md
  template.md
Labels: enhancement

#164 add markdownlint to ci
  .github/workflows/ci.yml
  anti_patterns/deref.md
  idioms/coercion-arguments.md
  idioms/mem-replace.md
  idioms/rustdoc-init.md
  patterns/RAII.md
  patterns/newtype.md
Labels: CI, enhancement

#166 Update rustdoc-init.md
  idioms/rustdoc-init.md
Labels: fix

#106 Several FFI Sections: Strings, Errors, and API Design
  README.md
  SUMMARY.md
  idioms/ffi-accepting-strings.md
  idioms/ffi-errors.md
  idioms/ffi-intro.md
  idioms/ffi-passing-strings.md
  patterns/ffi-export.md
  patterns/ffi-intro.md
  patterns/ffi-wrappers.md
Labels: LGTM, addition

#161 Writing an introduction for the Contribution guide
  CONTRIBUTING.md
Labels: enhancement, review

#158 Adding informative links to Builder
  patterns/builder.md
Labels: enhancement, review

#159 Adding more to additional resources
  additional_resources.md
Labels: addition, review

#169 Fix typo
  CONTRIBUTING.md
Labels: fix

#174 ci: simplify lint job
  .github/workflows/ci.yml
Labels: fix

#173 contributing: add markdown lints
  CONTRIBUTING.md
Labels: enhancement

#181 Updating Contrib
  CONTRIBUTING.md
  README.md
Labels: enhancement

#178 do not allow tabs in code blocks
  .markdownlint.yaml
  functional/index.md
  idioms/pass-var-to-closure.md
  idioms/temporary-mutability.md
Labels: CI, needed-discussion

#179 Adding design principles overview to additional resources
  SUMMARY.md
  design-principles.md
Labels: addition

#168 Add note on #[non_exhaustive] for enums
  idioms/priv-extend.md
Labels: enhancement

#183 add markdown rules
  .markdownlint.yaml
Labels: enhancement

#186 create additional_resources directory
  SUMMARY.md
  additional_resources/design-principles.md
  additional_resources/index.md
Labels: enhancement

#187 remove contributing from book
  SUMMARY.md
  intro.md
Labels: enhancement

#188 intro: split lines
  intro.md
Labels: enhancement

#189 Fix lines to 150 line length for better tracking of future changes
  .markdownlint.yaml
  CONTRIBUTING.md
  README.md
  additional_resources/design-principles.md
  anti_patterns/index.md
  functional/index.md
  idioms/coercion-arguments.md
  idioms/ffi-accepting-strings.md
  idioms/ffi-passing-strings.md
  idioms/index.md
  idioms/option-iter.md
  idioms/priv-extend.md
  idioms/rustdoc-init.md
  patterns/builder.md
  patterns/ffi-export.md
  patterns/ffi-wrappers.md
  patterns/index.md
  patterns/newtype.md
  patterns/small-crates.md
  refactoring/index.md
Labels: enhancement

#146 Strategy
  .gitignore
  SUMMARY.md
  patterns/strategy.md
Labels: addition, review

#200 Talk about mem::take instead of mem::replace
  SUMMARY.md
  idioms/mem-replace.md
Labels: enhancement

#201 CONTRIBUTING: add style guide
  CONTRIBUTING.md
Labels: review

#184 create separated page in functional programming
  SUMMARY.md
  functional/index.md
  functional/paradigms.md
Labels: enhancement

#209 Updating mdbook to v0.4.6
  .env
Labels: CI, enhancement

#208 Shorten lines to line-length 80
  .markdownlint.yaml
  CONTRIBUTING.md
  README.md
  additional_resources/design-principles.md
  additional_resources/index.md
  anti_patterns/index.md
  functional/paradigms.md
  idioms/coercion-arguments.md
  idioms/ctor.md
  idioms/ffi-accepting-strings.md
  idioms/ffi-errors.md
  idioms/ffi-intro.md
  idioms/ffi-passing-strings.md
  idioms/index.md
  idioms/option-iter.md
  idioms/pass-var-to-closure.md
  idioms/priv-extend.md
  idioms/rustdoc-init.md
  idioms/temporary-mutability.md
  intro.md
  patterns/RAII.md
  patterns/builder.md
  patterns/compose-structs.md
  patterns/ffi-export.md
  patterns/ffi-intro.md
  patterns/ffi-wrappers.md
  patterns/index.md
  patterns/newtype.md
  patterns/small-crates.md
  patterns/strategy.md
  patterns/unsafe-mods.md
  refactoring/index.md
Labels: enhancement, maintenance

#213 Remove lints that have been removed
  anti_patterns/deny-warnings.md
Labels: anti-pattern, fix

#215 Add note about delegation crates to Deref anti-pattern
  anti_patterns/deref.md
Labels: anti-pattern, enhancement
